### ISSUE TITLE
First python script completed

### ISSUE THREAD

**Issue by regnava** [madisoncollege-it-programs/python-scripting-regnava#2]

**Comment by cethenmc** [comment]
Hi, Mike.  I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
    1. modify the file in NetLab with the added line at the top.
    2. update the file to be executable.
    3. add the file to staging (git add .)
    4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    5. push to the git hub repository (git push)
    6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by cethenmc** [comment]
Mike - I await your reply when you have made it executable at the command line.  Thanks. ~Chris

**Comment by regnava** [comment]
I added the requested features to the prior scripts.

**Comment by cethenmc** [comment]
I do not see a change to make the script executable.  Please feel free to book me through Blackboard > Instructor Contact to book a meeting.  We have entered Week 6, and this file is still from Week 2.  We have a lot of catch-up to ensure all scripts between then and now can execute.  Thanks.  ~Chris

**Comment by regnava** [comment]
Looks like I made the changes but didn't send it to github. The content should be correct now.

**Comment by cethenmc** [comment]
Hi, Mike.  Week 2 through week 4 are not executing from the command line yet.  Are you sure you tested them on your side first.  If your answer is yes, are you sure you pushed to git hub after fully committing?  Please be sure to follow instructions, including the file names.  Week 3 I believe you named your file differently than the instructions requested.

Week 2 and 3 don't have executable permissions yet.  Week 4 does have executable permissions set, but your shebang line (the #! Line immediately at the top has an issue).  As a result, you get this error when trying to run it:  usr/bin/env:  bad interpreter:  No such file or directory.

Please don't hesitate to reach out if this is not making sense to you.

Thanks.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Mike - This one is now graded.  you need to submit an Issue Ticket for every script that is ready to grade.  I will place all comments in these issues for each assignment.  I will close the tickets only when they have been finally graded. As of now, you appear to be way behind in the course.  However, I see some files in GitHub all of the way into boolean.py in week6.  You **must** create a ticket, for each assignment each week.  As a result you are going into the midterm without graded work to see how you are doing.  You did send me an email response that you updated week 2 through 4, but I do not see an issue created for each of these to record my responses.  Please take care of this ASAP.  Thanks.  ~Chris
