### ISSUE TITLE
week4  -  thinking this is Week 7 Dictionaries that was saved to week4 accidentally.

### ISSUE THREAD

**Issue by regnava** [madisoncollege-it-programs/python-scripting-regnava#4]

**Comment by cethenmc** [comment]
I see that you put dictionaries from week 7 in week 4.  I wonder if this is why you have two week4 GitHub Issue Ticket entries.  

I will change this to week7 dictionaries.  2, 3, 6, and 7 are incorrect. 2 and 3 are missing a record; 6 and 7 aren't testing the search string requested to be searched.  On this one, you would have been better to not over complicate the dictionary.  No Author and Description shown on this lab.  Recording 4 out of 8.  Feel free to rework by Friday for full credit.

**Comment by cethenmc** [comment]
Locking the grade.  Closing ticket.
